>P1;hT2R10
sequence:hT2R10:1:.:307:.:.:.:.:sp|Q9NYW0|T2R10_HUMAN 307 residues
-------------------------------MLR--VVEGIFIFVVVSESVFGVLGNGFIGLVNCID--CAK
N-KLS--TIGFILTGLAISRIFLIWIIITDGFIQIF--SPNIYASGNLIE-----YISYFWVIGNQSSMWFA
TSLSIFYFLKIANFS--NYIFL---WLK------SRTNMVLPFMIVFLLISSLLNFA-----------YIAK
ILNDYKTKNDTVWDLNMYKSEYF---------IKQILLNLGVIFFFTLSLITCIFLIISLW--RHNRQMQSN
VTGLR--DSNTEAHVKAMKVLISFIILFILYFIGMAIEISCFTV----------------RENK--LLLMFG
MTTTAIYPWGHSFILI--LGNSKLKQASLRVLQQLKCCEKRKNLRVT----------------*
>P1;hT2R14
sequence:hT2R14:1:.:317:.:.:.:.:sp|Q9NYV8|T2R14_HUMAN 317 residues
-------------------------------MGG--VIKSIFTFVLIVEFIIGNLGNSFIALVNCID--WVK
GRKIS--SVDRILTALAISRISLVWLIFGSWCVSVF--FPALFATEKMFR-----MLTNIWTVINHFSVWLA
TGLGTFYFLKIANFS--NSIFL---YLK------WRVKKVVLVLLLVTSVFLFLNIA--------LINIHIN
ASINGYRRNKTCSSDSSNFTRFSS--------LIVLTSTVFIFIPFTLSLAMFLLLIFSMW--KHRKKMQHT
VKISG--DASTKAHRGVKSVITFFLLYAIFSLSFFISVWTSERL------------------EE--NLIILS
QVMGMAYPSCHSCVLI--LGNKKLRQASLSVLLWLRYMFKDGEPSGHKEFRESS---------*
>P1;hT2R16
sequence:hT2R16:1:.:291:.:.:.:.:sp|Q9NYV7|T2R16_HUMAN 291 residues
------------------------------MIPI--QLTVFFMIIYVLESLTIIVQSSLIVAVLGRE--WLQ
VRRLM--PVDMILISLGISRFCLQWASMLNNFCSYF--NLN-Y--VLC-------NLTITWEFFNILTFWLN
SLLTVFYCIKVSSFT--HHIFL---WLR------WRILRLFPWILLGSLMITCVTII---PSAIGNYIQIQL
LTMEHLPRNSTVTDKLENFHQ-----------YQFQAHTVALVIPFILFLASTIFLMASLT--KQIQ---HH
STGHC--NPSMKARFTALRSLAVLFIVFTSYFLTILITIIGTLF-----------------DKR--CWLWVW
EAFVYAFILMHSTSLM--LSSPTLKRILKGKC-------------------------------*
>P1;hT2R46
sequence:hT2R46:1:.:309:.:.:.:.:sp|P59540|T2R46_HUMAN 309 residues
-------------------------------MIT--FLPIIFSILIVVTFVIGNFANGFIALVNSIE--WFK
RQKIS--FADQILTALAVSRVGLLWVLVLNWYATEL--NPAFNS-IEVRI-----TAYNVWAVINHFSNWLA
TSLSIFYLLKIANFS--NLIFL---HLK------RRVKSVVLVILLGPLLFLVCHLF--------VINMNQI
IWTKEYEGNMTWKIKLRSAMYL----------SNTTVTILANLVPFTLTLISFLLLICSLC--KHLKKMQLH
GKGSQ--DPSMKVHIKALQTVTSFLLLCAIYFLSIIMSVWSFES----------------LENK--PVFMFC
EAIAFSYPSTHPFILI--WGNKKLKQTFLSVLWHVRYWVKGEKPSSS----------------*
>P1;hT2R1
sequence:hT2R1:1:.:299:.:.:.:.:sp|Q9NYW7|TA2R1_HUMAN 299 residues
-------------------------------MLE--SHLIIYFLLAVIQFLLGIFTNGIIVVVNGID--LIK
HRKMA--PLDLLLSCLAVSRIFLQLFIFYVNVIVIF--FIE----FIMCS-----ANCAILLFINELELWLA
TWLGVFYCAKVASVR--HPLFI---WLK------MRISKLVPWMILGSLLYVSMICV---FHSKYAGFMVPY
FLRKFFSQNATIQKEDTLA-------------IQIFSFVAEFSVPLLIFLFAVLLLIFSLG--RHTRQMRNT
VAGSR--VPGRGAPISALLSILSFLILYFSHCMIKVFLSSLKFH-----------------IRR--FIFLFF
ILVIGIYPSGHSLILI--LGNPKLKQNAKKFLLHSKCCQ------------------------*
>P1;hT2R3
sequence:hT2R3:1:.:316:.:.:.:.:sp|Q9NYW6|TA2R3_HUMAN 316 residues
-------------------------------MMG--LTEGVFLILSGTQFTLGILVNCFIELVNGSS--WFK
TKRMS--LSDFIITTLALLRIILLCIILTDSFLIEF--SPNTHDSGIIMQ-----IIDVSWTFTNHLSIWLA
TCLGVLYCLKIASFS--HPTFL---WLK------WRVSRVMVWMLLGALLLSCGSTA----SLINEFKLYSV
FRGIEATRNVTEHFRKKRSEYY----------LIHVLGTLWYLPPLIVSLASYSLLIFSLG--RHTRQMLQN
GTSSR--DPTTEAHKRAIRIILSFFFLFLLYFLAFLIASFGNFL----------------PKTK--MAKMIG
EVMTMFYPAGHSFILI--LGNSKLKQTFVVMLRCESGHLKPGSKGPIFS--------------*
>P1;hT2R4
sequence:hT2R4:1:.:299:.:.:.:.:sp|Q9NYW5|TA2R4_HUMAN 299 residues
-------------------------------MLR--LFYFSAIIASVILNFVGIIMNLFITVVNCKT--WVK
SHRIS--SSDRILFSLGITRFLMLGLFLVNTIYFVS-----SNTERSVYLSA---FFVLCFMFLDSSSVWFV
TLLNILYCVKITNFQ--HSVFL---LLK------RNISPKIPRLLLACVLISAFTTC-----LYITLSQASP
FPELVTTRNNTSFNISEGIL------------SLVVSLVLSSSLQFIINVTSASLLIHSLR--RHIQKMQKN
ATGFW--NPQTEAHVGAMKLMVYFLILYIPYSVATLVQYLPFYA----------------GMDM--GTKSIC
LIFATLYSPGHSVLII--ITHPKLKTTAKKILCFKK---------------------------*
>P1;hT2R5
sequence:hT2R5:1:.:299:.:.:.:.:sp|Q9NYW4|TA2R5_HUMAN 299 residues
-------------------------------MLS--AGLGLLMLVAVVEFLIGLIGNGSLVVWSFRE--WIR
KFNWS--SYNLIILGLAGCRFLLQWLIILDLSLFP------LFQSSRWLR-----YLSIFWVLVSQASLWFA
TFLSVFYCKKITTFD--RPAYL---WLK------QRAYNLSLWCLLGYFIINLLLTV-----------QIGL
TFYHPPQGNSSIRYPFESWQY-----------LYAFQLNSGSYLPLVVFLVSSGMLIVSLY--THHKKMKVH
SAGRR--DVRAKAHITALKSLGCFLLLHLVYIMASPFSITSKTY----------------PPDL--TSVFIW
ETLMAAYPSLHSLILI--MGIPRVKQTCQKILWKTVCARRCWGP-------------------*
>P1;hT2R7
sequence:hT2R7:1:.:318:.:.:.:.:sp|Q9NYW3|TA2R7_HUMAN 318 residues
-------------------------------MAD--KVQTTLLFLAVGEFSVGILGNAFIGLVNCMD--WVK
KRKIA--SIDLILTSLAISRICLLCVILLDCFILVL--YPDVYATGKEMR-----IIDFFWTLTNHLSIWFA
TCLSIYYFFKIGNFF--HPLFL---WMK------WRIDRVISWILLGCVVLSVFISL---PATENLNADFRF
CVKAKRKTNLTWSCRVNKTQHA----------STKLFLNLATLLPFCVCLMSFFLLILSLR--RHIRRMQLS
ATGCR--DPSTEAHVRALKAVISFLLLFIAYYLSFLIATSSYFM----------------PETE--LAVIFG
ESIALIYPSSHSFILI--LGNNKLRHASLKVIWKVMSILKGRKFQQHKQI-------------*
>P1;hT2R8
sequence:hT2R8:1:.:309:.:.:.:.:sp|Q9NYW2|TA2R8_HUMAN 309 residues
-------------------------------MFS--PADNIFIILITGEFILGILGNGYIALVNWID--WIK
KKKIS--TVDYILTNLVIARICLISVMVVNGIVIVL--NPDVYTKNKQQI-----VIFTFWTFANYLNMWIT
TCLNVFYFLKIASSS--HPLFL---WLK------WKIDMVVHWILLGCFAISLLVSL---IAAIVLSCDYRF
HAIAKHKRNITEMFHVSKIPYF----------EPLTLFNLFAIVPFIVSLISFFLLVRSLW--RHTKQIKLY
ATGSR--DPSTEVHVRAIKTMTSFIFFFFLYYISSILMTFSYLM----------------TKYK--LAVEFG
EIAAILYPLGHSLILI--VLNNKLRQTFVRMLTCRKIACMI----------------------*
>P1;hT2R9
sequence:hT2R9:1:.:312:.:.:.:.:sp|Q9NYW1|TA2R9_HUMAN 312 residues
-------------------------------MPS--AIEAIYIILIAGELTIGIWGNGFIVLVNCID--WLK
RRDIS--LIDIILISLAISRICLLCVISLDGFFMLL--FPGTYGNSVLVS-----IVNVVWTFANNSSLWFT
SCLSIFYLLKIANIS--HPFFF---WLK------LKINKVMLAILLGSFLISLIISV------PKNDDMWYH
LFKVSHEENITWKFKVSKIPGT----------FKQLTLNLGVMVPFILCLISFFLLLFSLV--RHTKQIRLH
ATGFR--DPSTEAHMRAIKAVIIFLLLLIVYYPVFLVMTSSALI----------------PQGK--LVLMIG
DIVTVIFPSSHSFILI--MGNSKLREAFLKMLRFVKCFLRRRKPFVP----------------*
>P1;hT2R13
sequence:hT2R13:1:.:303:.:.:.:.:sp|Q9NYV9|T2R13_HUMAN 303 residues
-------------------------------MES--ALPSIFTLVIIAEFIIGNLSNGFIVLINCID--WVS
KRELS--SVDKLLIILAISRIGLIWEILVSWFLALH--YLAIFVSGTGLR-----IMIFSWIVSNHFNLWLA
TIFSIFYLLKIASFS--SPAFL---YLK------WRVNKVILMILLGTLVFLFLNLI--------QINMHIK
DWLDRYERNTTWNFSMSDFETFSV--------SVKFTMTMFSLTPFTVAFISFLLLIFSLQ--KHLQKMQLN
YKGHR--DPRTKVHTNALKIVISFLLFYASFFLCVLISWISELY-----------------QNT--VIYMLC
ETIGVFSPSSHSFLLI--LGNAKLRQAFLLVAAKVWAKR------------------------*
>P1;hT2R19
sequence:hT2R19:1:.:299:.:.:.:.:sp|P59542|T2R19_HUMAN 299 residues
-------------------------------MMC--FLLIISSILVVFAFVLGNVANGFIALVNVID--WVN
TRKIS--SAEQILTALVVSRIGLLWVMLFLWYATVF--NSALYG-LEVRI-----VASNAWAVTNHFSMWLA
ASLSIFCLLKIANFS--NLISL---HLK------KRIKSVVLVILLGPLVFLICNLA--------VITMDER
VWTKEYEGNVTWKIKLRNAIHL----------SSLTVTTLANLIPFTLSLICFLLLICSLC--KHLKKMRLH
SKGSQ--DPSTKVHIKALQTVTSFLMLFAIYFLCIITSTWNLRT----------------QQSK--LVLLLC
QTVAIMYPSFHSFILI--MGSRKLKQTFLSVLWQMTR--------------------------*
>P1;hT2R20
sequence:hT2R20:1:.:309:.:.:.:.:sp|P59543|T2R20_HUMAN 309 residues
-------------------------------MMS--FLHIVFSILVVVAFILGNFANGFIALINFIA--WVK
RQKIS--SADQIIAALAVSRVGLLWVILLHWYSTVL--NPTSSN-LKVII-----FISNAWAVTNHFSIWLA
TSLSIFYLLKIVNFS--RLIFH---HLK------RKAKSVVLVIVLGSLFFLVCHLV--------MKHTYIN
VWTEECEGNVTWKIKLRNAMHL----------SNLTVAMLANLIPFTLTLISFLLLIYSLC--KHLKKMQLH
GKGSQ--DPSTKIHIKALQTVTSFLILLAIYFLCLIISFWNFKM----------------RPKE--IVLMLC
QAFGIIYPSFHSFILI--WGNKTLKQTFLSVLWQVTCWAKGQNQSTP----------------*
>P1;hT2R30
sequence:hT2R30:1:.:319:.:.:.:.:sp|P59541|T2R30_HUMAN 319 residues
-------------------------------MIT--FLPIIFSILIVVIFVIGNFANGFIALVNSIE--WVK
RQKIS--FVDQILTALAVSRVGLLWVLLLHWYATQL--NPAFYS-VEVRI-----TAYNVWAVTNHFSSWLA
TSLSMFYLLRIANFS--NLIFL---RIK------RRVKSVVLVILLGPLLFLVCHLF--------VINMDET
VWTKEYEGNVTWKIKLRSAMYH----------SNMTLTMLANFVPLTLTLISFLLLICSLC--KHLKKMQLH
GKGSQ--DPSTKVHIKALQTVTSFLLLCAIYFLSMIISVCNFGR----------------LEKQ--PVFMFC
QAIIFSYPSTHPFILI--LGNKKLKQIFLSVLRHVRYWVKDRSLRLHRFTRGALCVF------*
>P1;hT2R31
sequence:hT2R31:1:.:309:.:.:.:.:sp|P59538|T2R31_HUMAN 309 residues
-------------------------------MTT--FIPIIFSSVVVVLFVIGNFANGFIALVNSIE--RVK
RQKIS--FADQILTALAVSRVGLLWVLLLNWYSTVF--NPAFYS-VEVRT-----TAYNVWAVTGHFSNWLA
TSLSIFYLLKIANFS--NLIFL---HLK------RRVKSVILVMLLGPLLFLACQLF--------VINMKEI
VRTKEYEGNLTWKIKLRSAVYL----------SDATVTTLGNLVPFTLTLLCFLLLICSLC--KHLKKMQLH
GKGSQ--DPSTKVHIKALQTVIFFLLLCAVYFLSIMISVWSFGS----------------LENK--PVFMFC
KAIRFSYPSIHPFILI--WGNKKLKQTFLSVLRQVRYWVKGEKPSSP----------------*
>P1;hT2R38
sequence:hT2R38:1:.:333:.:.:.:.:sp|P59533|T2R38_HUMAN 333 residues
----------------------MLTLTRIRTVSY--EVRSTFLFISVLEFAVGFLTNAFVFLVNFWD--VVK
RQALS--NSDCVLLCLSISRLFLHGLLFLSAIQLTH--FQK-LSEPLNHSYQ---AIIMLWMIANQANLWLA
ACLSLLYCSKLIRFS--HTFLI---CLA------SWVSRKISQMLLGIILCSCICTV--LCVWCFFSRPHFT
VTTVLFMNNNTRLNWQIKDLNLF---------YSFLFCYLWSVPPFLLFLVSSGMLTVSLG--RHMRTMKVY
TRNSR--DPSLEAHIKALKSLVSFFCFFVISSCAAFISVPLLIL----------------WRDK--IGVMVC
VGIMAACPSGHAAILI--SGNAKLRRAVMTILLWAQSSLKVRADHKADSRTLC----------*
>P1;hT2R39
sequence:hT2R39:2:.:339:.:.:.:.:sp|P59534|T2R39_HUMAN 337 residues
---MLGRCFPPDTKEKQQLRMTKLCDPAESELSP--FLITLILAVLLAEYLIGIIANGFIMAIHAAE--WVQ
NKAVS--TSGRILVFLSVSRIALQSLMMLEITISST--SLSFYSEDAVYY-----AFKISFIFLNFCSLWFA
AWLSFFYFVKIANFS--YPLFL---KLR------WRITGLIPWLLWLSVFISFSHSM----FCINICTVYCN
NSFPIHSSNSTKKTYLSEINVV----------GLAFFFNLGIVTPLIMFILTATLLILSLK--RHTLHMGSN
ATGSN--DPSMEAHMGAIKAISYFLILYIFNAVALFIYLSNMFD-----------------INS--LWNNLC
QIIMAAYPASHSILLI--QDNPGLRRAWKRLQLRLHLYPKEWTL-------------------*
>P1;hT2R40
sequence:hT2R40:1:.:323:.:.:.:.:sp|P59535|T2R40_HUMAN 323 residues
-------------------MATVNTDATDKDISK--FKVTFTLVVSGIECITGILGSGFITAIYGAE--WAR
GKTLP--TGDRIMLMLSFSRLLLQIWMMLENIFSLL--FRIVYNQNSVYI-----LFKVITVFLNHSNLWFA
AWLKVFYCLRIANFN--HPLFF---LMK------RKIIVLMPWLLRLSVLVSLSFSF--PLSRDVFNV-YVN
SSIPIPSSNSTEKKYFSETNMV----------NLVFFYNMGIFVPLIMFILAATLLILSLK--RHTLHMGSN
ATGSR--DPSMKAHIGAIKATSYFLILYIFNAIALFLSTSNIFD-----------------TYS--SWNILC
KIIMAAYPAGHSVQLI--LGNPGLRRAWKRFQHQVPLYLKGQTL-------------------*
>P1;hT2R41
sequence:hT2R41:1:.:307:.:.:.:.:sp|P59536|T2R41_HUMAN 307 residues
-------------------------------MQA--ALTAFFVLLFSLLSLLGIAANGFIVLVLGRE--WLR
YGRLL--PLDMILISLGASRFCLQLVGTVHNFYYSA--QKVEYSGGLGRQ-----FFHLHWHFLNSATFWFC
SWLSVLFCVKIANIT--HSTFL---WLK------WRFPGWVPWLLLGSVLISFIITL--L-FFWVNYPVYQE
FLIRKFSGNMTYKWNT-RIETY----------YFPSLKLVIWSIPFSVFLVSIMLLINSLR--RHTQRMQHN
GHSLQ--DPSTQAHTRALKSLISFLILYALSFLSLIIDAAKFIS-----------------MQN--DFYWPW
QIAVYLCISVHPFILI--FSNLKLRSVFSQLLLLARGFWVA----------------------*
>P1;hT2R42
sequence:hT2R42:1:.:314:.:.:.:.:sp|Q7RTR8|T2R42_HUMAN 314 residues
-------------------------------MAT--ELDKIFLILAIAEFIISMLGNVFIGLVNCSE--GIK
NQKVF--SADFILTCLAISTIGQLLVILFDSFLVGL--ASHLYTTYRLGK-----TVIMLWHMTNHLTTWLA
TCLSIFYFFKIAHFP--HSLFL---WLR------WRMNGMIVMLLILSLFLLIFDSL-------VLEIFIDI
SLNIIDKSNLTLYLDESKTLYDKLS-------ILKTLLSLTSFIPFSLFLTSLLFLFLSLV--RHTRNLKLS
SLGSR--DSSTEAHRRAMKMVMSFLFLFIVHFFSLQVANGIFFM----------------LWNN--KYIKFV
MLALNAFPSCHSFILI--LGNSKLRQTAVRLLWHLRNYTKTPNALPL----------------*
>P1;hT2R43
sequence:hT2R43:1:.:309:.:.:.:.:sp|P59537|T2R43_HUMAN 309 residues
-------------------------------MIT--FLPIIFSSLVVVTFVIGNFANGFIALVNSIE--WFK
RQKIS--FADQILTALAVSRVGLLWVLLLNWYSTVL--NPAFNS-VEVRT-----TAYNIWAVINHFSNWLA
TTLSIFYLLKIANFS--NFIFL---HLK------RRVKSVILVMLLGPLLFLACHLF--------VINMNEI
VRTKEFEGNMTWKIKLKSAMYF----------SNMTVTMVANLVPFTLTLLSFMLLICSLC--KHLKKMQLH
GKGSQ--DPSTKVHIKALQTVISFLLLCAIYFLSIMISVWSFGS----------------LENK--PVFMFC
KAIRFSYPSIHPFILI--WGNKKLKQTFLSVFWQMRYWVKGEKTSSP----------------*
>P1;hT2R45
sequence:hT2R45:1:.:299:.:.:.:.:sp|P59539|T2R45_HUMAN 299 residues
-------------------------------MIT--FLPIIFSILVVVTFVIGNFANGFIALVNSTE--WVK
RQKIS--FADQIVTALAVSRVGLLWVLLLNWYSTVL--NPAFCS-VELRT-----TAYNIWAVTGHFSNWPA
TSLSIFYLLKIANFS--NLIFL---RLK------RRVKSVILVVLLGPLLFLACHLF--------VVNMNQI
VWTKEYEGNMTWKIKLRRAMYL----------SDTTVTMLANLVPFTVTLISFLLLVCSLC--KHLKKMQLH
GKGSQ--DPSTKVHIKVLQTVISFFLLRAIYFVSVIISVWSFKN----------------LENK--PVFMFC
QAIGFSCSSAHPFILI--WGNKKLKQTYLSVLWQMRY--------------------------*
>P1;hT2R50
sequence:hT2R50:1:.:299:.:.:.:.:sp|P59544|T2R50_HUMAN 299 residues
-------------------------------MIT--FLYIFFSILIMVLFVLGNFANGFIALVNFID--WVK
RKKIS--SADQILTALAVSRIGLLWALLLNWYLTVL--NPAFYS-VELRI-----TSYNAWVVTNHFSMWLA
ANLSIFYLLKIANFS--NLLFL---HLK------RRVRSVILVILLGTLIFLVCHLL--------VANMDES
MWAEEYEGNMTGKMKLRNTVHL----------SYLTVTTLWSFIPFTLSLISFLMLICSLC--KHLKKMQLH
GEGSQ--DLSTKVHIKALQTLISFLLLCAIFFLFLIVSVWSPRR----------------LRND--PVVMVS
KAVGNIYLAFDSFILI--WRTKKLKHTFLLILCQIRC--------------------------*
>P1;hT2R60
sequence:hT2R60:1:.:318:.:.:.:.:sp|P59551|T2R60_HUMAN 318 residues
--------------------MNGDHMVLGSSVTD--KKAIILVTILLLLRLVAIAGNGFITAALGVE--WVL
RRMLL--PCDKLLVSLGASRFCLQSVVMGKTIYVFL--HPMAFPYNPVLQ-----FLAFQWDFLNAATLWSS
TWLSVFYCVKIATFT--HPVFF---WLK------HKLSGWLPWMLFSSVGLSSFTTI--LFFIGNHRMYQNY
LRNHLQPWNVTGDSIRSYCEKF----------YLFPLKMITWTMPTAVFFICMILLITSLG--RHRKKALLT
TSGFR--EPSVQAHIKALLALLSFAMLFISYFLSLVFSAAGIFP-----------------PLD--FKFWVW
ESVIYLCAAVHPIILL--FSNCRLRAVLKSRRSSRCGTP------------------------*
>P1;hOR1A2
sequence:hOR1A2:1:.:309:.:.:.:.:olfactory receptor 1A2 [Homo sapiens]
-------------MKKENQSFNLDFILLGVTSQQ--EQNNVFFVIFLCIYPITLTGNLLIILAICAD---IR
LHN----PMYFLLANLSLVDIIFSSVTIPKVLANHL----LGSKFISFG------GCLMQMYFMIALAKADS
YTLAAMAYDRAVAIS--CPLHYTT-IMSP-----RSCILLIAGSWVIGNTSALPHTL--------LTASLSF
CGNQEVANFYCDIMPLLKLSCSDVHFNV----KMMYLGVGVFSLPLL-CIIVSYVQVFSTV-----------
---FQ--VPSTKSLFKAFCTCGSHLTVVFLYYGTTMGMYFRPL---------------TSYSP---KDAVIT
VMYVAVTPALNPFIYS--LRNWDMKAALQKLFSKRISS-------------------------*
>P1;hOR1A1
sequence:hOR1A1:1:.:309:.:.:.:.:protein [Homo sapiens]
-------------MRENNQSSTLEFILLGVTGQQ--EQEDFFYILFLFIYPITLIGNLLIVLAICSD---VR
LHN----PMYFLLANLSLVDIFFSSVTIPKMLANHL----LGSKSISFG------GCLTQMYFMIALGNTDS
YILAAMAYDRAVAIS--RPLHYTT-IMSP-----RSCIWLIAGSWVIGNANALPHTL--------LTASLSF
CGNQEVANFYCDITPLLKLSCSDIHFHV----KMMYLGVGIFSVPLL-CIIVSYIRVFSTV-----------
---FQ--VPSTKGVLKAFSTCGSHLTVVSLYYGTVMGTYFRPL---------------TNYSL---KDAVIT
VMYTAVTPMLNSFIYS--LRNRDMKAALRKLFNKRISS-------------------------*
>P1;hOR1G1
sequence:hOR1G1:1:.:313:.:.:.:.:protein [Homo sapiens]
-------------MEGKNLTSISECFLLGFSEQL--EEQKPLFGSFLFMYLVTVAGNLLIILVIITD---TQ
LHT----PMYFFLANLSLADACFVSTTVPKMLANIQ----IQSQAISYS------GCLLQLYFFMLFVMLEA
FLLAVMAYDCYVAIC--HPLHYIL-IMSP-----GLCIFLVSASWIMNALHSLLHTL--------LMNSLSF
CANHEIPHFFCDINPLLSLSCTDPFTNE----LVIFITGGLTGLICVLCLIISYTNVFSTI-----------
---LK--IPSAQGKRKAFSTCSSHLSVVSLFFGTSFCVDFSSPS---------------THSAQ--KDTVAS
VMYTVVTPMLNPFIYS--LRNQEIKSSLRKLIWVRKIHSP-----------------------*
>P1;hOR2AG1
sequence:hOR2AG1:1:.:316:.:.:.:.:olfactory receptor 2AG1 [Homo sapiens]
-------------MELWNFTLGSGFILVGILNDS--GSPELLCATITILYLLALISNGLLLLAITME---AR
LHM----PMYLLLGQLSLMDLLFTSVVTPKALADFL----RRENTISFG------GCALQMFLALTMGGAED
LLLAFMAYDRYVAIC--HPLTYMT-LMSS-----RACWLMVATSWILASLSALIYTV--------YTMHYPF
CRAQEIRHLLCEIPHLLKVACADTSRYE----LMVYVMGVTFLIPSLAAILASYTQILLTV-----------
---LH--MPSNEGRKKALVTCSSHLTVVGMFYGAATFMYVLPSS---------------FHSTR--QDNIIS
VFYTIVTPALNPLIYS--LRNKEVMRALRRVLGKYMLPAHSTL--------------------*
>P1;6FUF:A/2-317
sequence:6FUF:2:.:317:.:.:.:.:6FUF
CGTEGPNFYVPFSNKTGVVRSPFEAP-QYYLAEP--WQFSMLAAYMFLLIMLGFPINFLTLYVTVQH---KK
LRT----PLNYILLNLAVADLFMVFGGFTTTLYTSL----HGYFVFGPT------GCNLEGFFATLGGEIAL
WSLVVLAIERYVVVC--KPMSN----FRFGE---NHAIMGVAFTWVMALACAAPPLV------------GWS
RYIPEGMQCSCGIDYYTPHEETNNES------FVIYMFVVHFIIPLIVIFFCYGQLVFTVK--EAA-----A
QQQES--ATTQKAEKEVTRMVIIYVIAFLICWLPYAGVAFYIFT---HQG---------SCFGP--IFMTIP
AFFAKTSAVYNPVIYI--MMNKQFRNCM-----------------------------------*
>P1;4BVN:A/36-258
sequence:4BVN:36:.:358:.:.:.:.:4BVN
-------------------------------LSQ--QWEAGMSLLMALVVLLIVAGNVLVIAAIGST---QR
LQT----LTNLFITSLACADLVVGLLVVPFGATLVV----RGTWLWGSF------LCELWTSLDVLCVTASV
ETLCVIAIDRYLAIT--SPFRYQSLMTR------ARAKVIICTVWAISALVSFLPIM-----MHWWRDEDPQ
ALKCYQDPGCCDFVTNRA--------------YAIASSIISFYIPLLIMIFVALRVYREAK--EQIRK----
-RKTS--RVMLMREHKALKTLGIIMGVFTLCWLPFFLVNIVNVF---N----------RDLVPK--WLFVAF
NWLGYANSAMNPIILC--R-SPDFRKAFKRLLA------------------------------*
>P1;5JQH:A/1027-1343
sequence:5JQH:1027:.:1343:.:.:.:.:5JQH
------------------------------AADE--VWVVGMGIVMSLIVLAIVFGNVLVITAIAKF---ER
LQT----VTNYFITSLACADLVMGLAVVPFGAAHIL----TKTWTFGNF------WCEFWTSIDVLCVTASI
ETLCVIAVDRYFAIT--SPFKYQSLLTK------NKARVIILMVWIVSGLTSFLPIQ-----MHWYRATHQE
AINCYAEETCCDFFTNQA--------------YAIASSIVSFYVPLVIMVFVYSRVFQEAK--RQL------
-------DKFALKEHKALKTLGIIMGTFTLCWLPFFIVNIVHVI---QD----------NLIRK--EVYILL
NWIGYVNSGFNPLIYC--R-SPDFRIAFQE-LLCLR---------------------------*
>P1;4YAY:A/12-317
sequence:4YAY:12:.:317:.:.:.:.:4YAY
--------------------ILNSSDCPKAGRHN--YIFVMIPTLYSIIFVVGIFGNSLVVIVIYFY---MK
LKT----VASVFLLNLALADLCFLL-TLPLWAVYTA---MEYRWPFGNY------LCKIASASVSFNLYASV
FLLTCLSIDRYLAIV--HPMKS--RLRRTM----LVAKVTCIIIWLLAGLAS-LPAI--------------I
HRNVFFIITVCAFHYETLPIG-----------LGLTKNILGFLFPFLIILTSYTLIWKALK--K--------
-------------NDDIFKIIMAIVLFFFFSWIPHQIFTFLDVL---IQLGIIRDCR-IADIVD--TAMPIT
ICIAYFNNCLNPLFYG--FLGKKFKRYFLQLL-------------------------------*
>P1;3ODU:A/27-329
sequence:3ODU:27:.:329:.:.:.:.:3ODU
-------------------------PCFREENAN--FNKIFLPTIYSIIFLTGIVGNGLVILVMGYQ---KK
LRS----MTDKYRLHLSVADLLFVI-TLPFWAVDAV-----ANWYFGNF------LCKAVHVIYTVNLYSSV
WILAFISLDRYLAIV--HATNS----QRPRKL--LAEKVVYVGVWIPALLLT-IPDF------------IFA
NVSEADDRYICDRFYPNDLWVVV---------FQFQHIMVGLILPGIVILSCYCIIISKLS--HSG------
---------KGHQKRKALKTTVILILAFFACWLPYYIGISIDSF---ILLEIIKQGCEFENTVH--KWISIT
EALAFFHCCLNPILYA--FLGAKFKTSAQHALTSGRPLEVLFQ--------------------*
>P1;6BQG:A/43-386
sequence:6BQG:43:.:386:.:.:.:.:6BQG
--------------------------GGRFKFPD--GVQNWPALSIVIIIIMTIGGNILVIMAVSME---KK
LHN----ATNYFLMSLAIADMLVGLLVMPLSLLAIL---YDYVWPLPRY------LCPVWISLDVLFSTASI
MHLCAISLDRYVAIR--NPIEH---NSR------TKAIMKIAIVWAISIGVS-VPIP---------VIGLRD
EEKVFVNNTTCVLNDPN---------------FVLIGSFVAFFIPLTIMVITYCLTIYVLR--RQA------
--------QAINNERKASKVLGIVFFVFLIMWCPFFITNILSVL---CEKSCN------QKLME--KLLNVF
VWIGYVNSGINPLVYT--LFNKIYRRAFSNYLRCN----------------------------*
